### ISSUE TITLE
    change_path = area + '/change.bmp'     un_path = area + '/unchange.bmp'

### ISSUE THREAD

**Issue by xautdestiny** [rulixiang/DSFANet#1]
do you have change.bmp and unchange.bmp?the change_ref is the same as unchange.bmp?

**Comment by rulixiang** [comment]
The value changed regions of change.bmp is 1, while the other regions' value is 0 (undefined and unchanged regions). Value of unchange.bmp is the opposite.

**Comment by xautdestiny** [comment]
Which data sets are your training data set and validation data set? How many images are there in the training data?
Must we use mat files for training? I want to use JPG file as training set. Is that OK?






can you speak chinese?


------------------ 原始邮件 ------------------
发件人: "LixiangRu"<notifications@github.com>;
发送时间: 2019年8月2日(星期五) 上午9:08
收件人: "rulixiang/DSFANet"<DSFANet@noreply.github.com>;
抄送: "1227482510"<1227482510@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [rulixiang/DSFANet]     change_path = area + '/change.bmp'    un_path = area + '/unchange.bmp' (#1)




The value changed regions of change.bmp is 1, while the other regions' value is 0 (undefined and unchanged regions). Value of unchange.bmp is the opposite.

**Comment by rulixiang** [comment]
训练数据不是一整张的图像，而是从图像中选取的像素点；
用的数据集之一是从[这](https://share.weiyun.com/5ugrczK)下载的
mat只是我用来存储数据的，任何能读成numpy矩阵（高x宽x波段）的数据格式都可以的。

**Comment by rulixiang** [comment]
可能是groundtruth.mat里面变化区域值是255，而我的cva_ind变化区域像素值是1，你可以试试把groundtruth除以255

**Comment by xautdestiny** [comment]
这个问题我已经想到了，并且已经将groundtruth.mat的[0,255]转换成[0,1]格式了，但是还是出现NAN的问题。
      在调试过程中，我发现我的change.bmp  unchange.bmp是二维图像，请问你的change.bmp是二维图像还是三维图像？会不会是我的change.bmp有错误。
      如果可以的话，能不能请您把您的ind.mat数据和change.bmp发我一份......
      谢谢您！




------------------ 原始邮件 ------------------
发件人: "LixiangRu"<notifications@github.com>;
发送时间: 2019年8月2日(星期五) 晚上9:38
收件人: "rulixiang/DSFANet"<DSFANet@noreply.github.com>;
抄送: "1227482510"<1227482510@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [rulixiang/DSFANet]     change_path = area + '/change.bmp'    un_path = area + '/unchange.bmp' (#1)




可能是groundtruth.mat里面变化区域值是255，而我的cva_ind变化区域像素值是1，你可以试试把groundtruth除以255

**Comment by rulixiang** [comment]
[river.zip](https://github.com/rulixiang/DSFANet/files/3461701/river.zip)

**Comment by xautdestiny** [comment]
收到了！非常感谢您的耐心！


------------------ 原始邮件 ------------------
发件人: "LixiangRu"<notifications@github.com>;
发送时间: 2019年8月2日(星期五) 晚上10:37
收件人: "rulixiang/DSFANet"<DSFANet@noreply.github.com>;
抄送: "1227482510"<1227482510@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [rulixiang/DSFANet]     change_path = area + '/change.bmp'    un_path = area + '/unchange.bmp' (#1)




river.zip

**Comment by xautdestiny** [comment]
我在使用了你的原数据之后，训练能顺利完成，精度还可以达到94%左右。非常理想！感谢大佬倾力相助，在此谢过
但是在变换了自己的数据集之后就出现了新的问题。




这个模型对于数据的格式有什么要求吗？
我的数据是我自己将960*960*3的tif文件转换成960*960*3的mat文件，为何会出现这种错误呢？




------------------ 原始邮件 ------------------
发件人: "LixiangRu"<notifications@github.com>;
发送时间: 2019年8月2日(星期五) 晚上10:37
收件人: "rulixiang/DSFANet"<DSFANet@noreply.github.com>;
抄送: "1227482510"<1227482510@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [rulixiang/DSFANet]     change_path = area + '/change.bmp'    un_path = area + '/unchange.bmp' (#1)




river.zip

**Comment by rulixiang** [comment]
这个代码还是像素级的变化检测，对中低分辨率效果还不错，但是高分辨率的影像不行；3个波段的数据我没测试过，不过我想多波段数据的结果会比3个波段的更好

**Comment by xautdestiny** [comment]
大佬，我又来了~~~
想知道在训练结束后，网络测试怎么做？对于无标签的数据，我们该怎么做呢？




------------------ 原始邮件 ------------------
发件人: "LixiangRu"<notifications@github.com>;
发送时间: 2019年8月3日(星期六) 中午12:32
收件人: "rulixiang/DSFANet"<DSFANet@noreply.github.com>;
抄送: "1227482510"<1227482510@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [rulixiang/DSFANet]     change_path = area + '/change.bmp'    un_path = area + '/unchange.bmp' (#1)




这个代码还是像素级的变化检测，对中低分辨率效果还不错，但是高分辨率的影像不行；3个波段的数据我没测试过，不过我想多波段数据的结果会比3个波段的更好

**Comment by rulixiang** [comment]
就是先用CVA预处理得到训练样本，之后运行代码，在dsfa.py里面，change_map就是整张图像的变化检测结果
```
    change_map = np.reshape(utils.kmeans(np.reshape(all_magnitude, [-1])), img_shape[0:-1])

    logging.info('Max value of change magnitude: %.4f'%(np.max(all_magnitude)))
    logging.info('Min value of change magnitude: %.4f'%(np.min(all_magnitude)))

    # magnitude
    acc_un, acc_chg, acc_all2, acc_tp = utils.metric(1-change_map, chg_map, un_map)
    acc_un, acc_chg, acc_all3, acc_tp = utils.metric(change_map, chg_map, un_map)
    plt.imshow(all_magnitude, cmap='gray')
    plt.show()
```
因为没有测试样本的标签，所以要把utils.metric注释掉
