### ISSUE TITLE
请问您说的“ B_inv, For numerical stability.”这部分的数学原理是什么呢？

### ISSUE THREAD

**Issue by GusRoth** [rulixiang/DSFANet#13]
![image](https://user-images.githubusercontent.com/43126958/89125378-94270680-d510-11ea-99c7-e02753ea32b0.png)
为什么要加这一步处理呢？论文中好像没有提到这一步处理。

**Comment by rulixiang** [comment]
您好，这一步的目的是为了求B矩阵的逆过程更加robust，这部分的代码是我在学习Deep Canonical Correlation Analysis的实现学到的，DCCA的开源代码您可以在github上找到很多；这部分没在论文中体现是因为它只是一个求逆的小技巧，所以没有提到。

**Comment by GusRoth** [comment]
@rulixiang 感谢您！我搜到了其他人写的，也知道是什么意思了。
我发现了一个问题，同样的参数以及其他不改变的情况下，如果将那部分为了数值稳定性的部分去掉直接改为求逆或者伪逆，效果就会不稳定，甚至结果预测几乎全白。所以说这部分还是很重要的吧

**Comment by GusRoth** [comment]
@rulixiang 此外请问您这个repo中给下载的数据中使用的pre detection的参考图像是如何获得的呢？论文中的河流数据也是基于pre detection的图像然后训练的结果嘛？

**Comment by rulixiang** [comment]
@GusRoth ，您好， predetection的结果就是用CVA进行变化检测的结果，CVA比较简单，相信您可以很容易实现。

**Comment by GusRoth** [comment]
> @GusRoth ，您好， predetection的结果就是用CVA进行变化检测的结果，CVA比较简单，相信您可以很容易实现。

（非常感谢您的指点！）*1000
最后还有一个疑问关于训练集和测试集，我理解的关于您使用的训练集是根据cva的predtection结果从这两张river图像中选择了对应的一系列像素点作为训练集进行训练，但是最后测试集同样也使用模型对这一图像进行测试。不知道是否哪里理解错了。如果是这样的话训练集和测试集有重合（虽然是部分重合）在某些情况下是被允许的嘛？感觉一般train-val-test的划分都是完全分开的。
再次感谢您！

**Comment by GusRoth** [comment]
> @GusRoth ，您好， predetection的结果就是用CVA进行变化检测的结果，CVA比较简单，相信您可以很容易实现。

对不起刚才问了个蠢问题，我刚开始接触无监督，和有监督搞混了，希望如果您看到了不要在意....
再次非常感谢您的耐心解答！
不过关于B求逆的过程，直接使用tf的求逆的话，训练的结果就会差非常多，所以一般求逆的话都会使用某些方法保证数值稳定性嘛？为什么会影响这么大呢，是哪些不鲁棒的情况导致的呀？
这可能是非常基础的数学知识，但是我基础比较薄弱，如果可以的话，希望您可以指给我一本书或者某一个范围我再去看看。

再次感谢您！！

**Comment by rulixiang** [comment]
抱歉，这个我也不清楚了，恐怕帮不了您了。 

> > @GusRoth ，您好， predetection的结果就是用CVA进行变化检测的结果，CVA比较简单，相信您可以很容易实现。
> 
> 对不起刚才问了个蠢问题，我刚开始接触无监督，和有监督搞混了，希望如果您看到了不要在意....
> 再次非常感谢您的耐心解答！
> 不过关于B求逆的过程，直接使用tf的求逆的话，训练的结果就会差非常多，所以一般求逆的话都会使用某些方法保证数值稳定性嘛？为什么会影响这么大呢，是哪些不鲁棒的情况导致的呀？
> 这可能是非常基础的数学知识，但是我基础比较薄弱，如果可以的话，希望您可以指给我一本书或者某一个范围我再去看看。
> 
> 再次感谢您！！

**Comment by GusRoth** [comment]
> 抱歉，这个我也不清楚了，恐怕帮不了您了。
> 
> > > @GusRoth ，您好， predetection的结果就是用CVA进行变化检测的结果，CVA比较简单，相信您可以很容易实现。
> > 
> > 
> > 对不起刚才问了个蠢问题，我刚开始接触无监督，和有监督搞混了，希望如果您看到了不要在意....
> > 再次非常感谢您的耐心解答！
> > 不过关于B求逆的过程，直接使用tf的求逆的话，训练的结果就会差非常多，所以一般求逆的话都会使用某些方法保证数值稳定性嘛？为什么会影响这么大呢，是哪些不鲁棒的情况导致的呀？
> > 这可能是非常基础的数学知识，但是我基础比较薄弱，如果可以的话，希望您可以指给我一本书或者某一个范围我再去看看。
> > 再次感谢您！！

谢谢您的指点！
