### ISSUE TITLE
problem about sigma in your code.

### ISSUE THREAD

**Issue by li-shipeng** [rulixiang/DSFANet#16]
it is obviously B_inv and A are self-adjoint matrices.
how to make sure sigma in https://github.com/rulixiang/DSFANet/blob/b18e93cb8011284e2cb03464bb727ba07698502d/model.py#L81 is a self-adjoint matrice, if you use tf.self_adjoint_eig.

**Comment by rulixiang** [comment]
Hi, thanks for pointing out my negligence. It seems his decomposition does not affect the calculation of the loss function and also the training process. Still, it will affect the computation of the projection matrix. For clearness and correctness, I refactored our code and fixed this error.
