### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by xautdestiny** [rulixiang/DSFANet#2]
Which data sets are your training data set and validation data set? How many images are there in the training data?

**Comment by Cherishaca** [comment]
hello.Can you run the program properly?and the data requirements?

**Comment by xautdestiny** [comment]
I can run, that is to say, the data needs to be a little complicated, and the image data format needs to be converted into mat file format.
 this is my data:







------------------ 原始邮件 ------------------
发件人: "Cherishaca"<notifications@github.com>;
发送时间: 2019年10月9日(星期三) 晚上10:12
收件人: "rulixiang/DSFANet"<DSFANet@noreply.github.com>;
抄送: "1227482510"<1227482510@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [rulixiang/DSFANet] datasets (#2)




hello.Can you run the program properly?and the data requirements?

**Comment by xautdestiny** [comment]
> hello.Can you run the program properly?and the data requirements?

Cherishaca：
I can run, that is to say, the data needs to be a little complicated, and the image data format needs to be converted into mat file format.

**Comment by Cherishaca** [comment]
Can you add my Wechat or QQ? Some questions want to consult you in time, my QQ and Wechat: 1561442219. Thank you

**Comment by ZhinanCai** [comment]
> 
> 
> Which data sets are your training data set and validation data set? How many images are there in the training data?

In my opinion, the data set only needs a pair of images.because its  an unsupervised method.

**Comment by xautdestiny** [comment]
这是我的训练数据，只用了一组数据，因为它是像素级的训练，验证用了很多组。





------------------ 原始邮件 ------------------
发件人: "ZhinanCai"<notifications@github.com>;
发送时间: 2019年10月11日(星期五) 晚上8:47
收件人: "rulixiang/DSFANet"<DSFANet@noreply.github.com>;
抄送: "1227482510"<1227482510@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [rulixiang/DSFANet] datasets (#2)



 
Which data sets are your training data set and validation data set? How many images are there in the training data?
  
In my opinion, the data set only needs a pair of images.because its  an unsupervised method.

**Comment by xautdestiny** [comment]
为什么要随机挑选样本？
随机挑选样本的依据是什么？
计算TP、TN、FP、FN的时候，是只计算了选取样本的正确率还是计算了整图结果的正确率？
论文中绿色代表不变区域，红色代表变化区域，那么为什么不选红色之外的所有样本都是不变区域呢？是为了样本均衡吗？还是有其他考虑？
你的ground-truth为什么要将建筑物或道路的边缘认为是变化呢，是像素对比后确实变化了吗？
像素级的变化可以应用在哪些地方？总觉得换个光学遥感3波段数据，检测结果很不好。。。


不好意思，问题有点多，望大神解答！！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"破铜烂铁  "<1227482510@qq.com&gt;;
发送时间:&nbsp;2019年10月14日(星期一) 下午4:44
收件人:&nbsp;"rulixiang/DSFANet"<reply@reply.github.com&gt;;

主题:&nbsp;回复： [rulixiang/DSFANet] datasets (#2)




这是我的训练数据，只用了一组数据，因为它是像素级的训练，验证用了很多组。





------------------ 原始邮件 ------------------
发件人:&nbsp;"ZhinanCai"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月11日(星期五) 晚上8:47
收件人:&nbsp;"rulixiang/DSFANet"<DSFANet@noreply.github.com&gt;;
抄送:&nbsp;"1227482510"<1227482510@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rulixiang/DSFANet] datasets (#2)



 
Which data sets are your training data set and validation data set? How many images are there in the training data?
  
In my opinion, the data set only needs a pair of images.because its  an unsupervised method.

**Comment by rulixiang** [comment]
你好，随机挑选样本并没有什么理论依据，你也可以尝试用预检测置信度最高的一定数量的样本进行训练；
计算tp、tn等指标的时候只用了图像中红色和绿色的区域，因为其他的区域没有对应的label，而且也不是很好标注；并且用的这些数据也并不是我标的，所以我也没有对原来的标注进行修改。
至于在用你的数据的实验结果并不是很好，原因我也不太清楚；但是这个网络结果比较依赖于CVA的预检测结果；并且我认为对中低分辨率的效果比高分影像的效果好；这些原因供您参考。

**Comment by xautdestiny** [comment]
你好，我在做CVA预处理的时候，有一些问题，应该是你的代码，matlab版的，如果可以的话，可以加一下我微信吗？方便沟通，不会打扰您，谢谢！！

















------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"LixiangRu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月14日(星期二) 晚上8:32
收件人:&nbsp;"rulixiang/DSFANet"<DSFANet@noreply.github.com&gt;;
抄送:&nbsp;"1227482510"<1227482510@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rulixiang/DSFANet] datasets (#2)




你好，随机挑选样本并没有什么理论依据，你也可以尝试用预检测置信度最高的一定数量的样本进行训练；
 计算tp、tn等指标的时候只用了图像中红色和绿色的区域，因为其他的区域没有对应的label，而且也不是很好标注；并且用的这些数据也并不是我标的，所以我也没有对原来的标注进行修改。
 至于在用你的数据的实验结果并不是很好，原因我也不太清楚；但是这个网络结果比较依赖于CVA的预检测结果；并且我认为对中低分辨率的效果比高分影像的效果好；这些原因供您参考。

**Comment by Cherishaca** [comment]
可以，你微信是多少？
  

 

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"xautdestiny"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年1月15日(星期三) 中午11:34
 收件人:&nbsp;"rulixiang/DSFANet"<DSFANet@noreply.github.com&gt;;
 抄送:&nbsp;"&nbsp;"<1561442219@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
 主题:&nbsp;Re: [rulixiang/DSFANet] datasets (#2)

 

你好，我在做CVA预处理的时候，有一些问题，应该是你的代码，matlab版的，如果可以的话，可以加一下我微信吗？方便沟通，不会打扰您，谢谢！！ 

















------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
发件人:&amp;nbsp;"LixiangRu"<notifications@github.com&amp;gt;; 
发送时间:&amp;nbsp;2020年1月14日(星期二) 晚上8:32 
收件人:&amp;nbsp;"rulixiang/DSFANet"<DSFANet@noreply.github.com&amp;gt;; 
抄送:&amp;nbsp;"1227482510"<1227482510@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
主题:&amp;nbsp;Re: [rulixiang/DSFANet] datasets (#2) 




你好，随机挑选样本并没有什么理论依据，你也可以尝试用预检测置信度最高的一定数量的样本进行训练； 
计算tp、tn等指标的时候只用了图像中红色和绿色的区域，因为其他的区域没有对应的label，而且也不是很好标注；并且用的这些数据也并不是我标的，所以我也没有对原来的标注进行修改。 
至于在用你的数据的实验结果并不是很好，原因我也不太清楚；但是这个网络结果比较依赖于CVA的预检测结果；并且我认为对中低分辨率的效果比高分影像的效果好；这些原因供您参考。

**Comment by xautdestiny** [comment]
你可以扫我的二维码，谢谢！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cherishaca"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月12日(星期三) 下午3:20
收件人:&nbsp;"rulixiang/DSFANet"<DSFANet@noreply.github.com&gt;;
抄送:&nbsp;"1227482510"<1227482510@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rulixiang/DSFANet] datasets (#2)



可以，你微信是多少？ 
    
 
   
 
  ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
   发件人:&amp;nbsp;"xautdestiny"<notifications@github.com&amp;gt;; 
  发送时间:&amp;nbsp;2020年1月15日(星期三) 中午11:34 
  收件人:&amp;nbsp;"rulixiang/DSFANet"<DSFANet@noreply.github.com&amp;gt;; 
  抄送:&amp;nbsp;"&amp;nbsp;"<1561442219@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
  主题:&amp;nbsp;Re: [rulixiang/DSFANet] datasets (#2) 
 
   
 
 你好，我在做CVA预处理的时候，有一些问题，应该是你的代码，matlab版的，如果可以的话，可以加一下我微信吗？方便沟通，不会打扰您，谢谢！！  
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
 发件人:&amp;amp;nbsp;"LixiangRu"<notifications@github.com&amp;amp;gt;;  
 发送时间:&amp;amp;nbsp;2020年1月14日(星期二) 晚上8:32  
 收件人:&amp;amp;nbsp;"rulixiang/DSFANet"<DSFANet@noreply.github.com&amp;amp;gt;;  
 抄送:&amp;amp;nbsp;"1227482510"<1227482510@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
 主题:&amp;amp;nbsp;Re: [rulixiang/DSFANet] datasets (#2)  
 
 
 
 
 你好，随机挑选样本并没有什么理论依据，你也可以尝试用预检测置信度最高的一定数量的样本进行训练；  
 计算tp、tn等指标的时候只用了图像中红色和绿色的区域，因为其他的区域没有对应的label，而且也不是很好标注；并且用的这些数据也并不是我标的，所以我也没有对原来的标注进行修改。  
 至于在用你的数据的实验结果并不是很好，原因我也不太清楚；但是这个网络结果比较依赖于CVA的预检测结果；并且我认为对中低分辨率的效果比高分影像的效果好；这些原因供您参考。
