### ISSUE TITLE
求损失函数的时候为什么要给B加正则化项

### ISSUE THREAD

**Issue by ZhinanCai** [rulixiang/DSFANet#3]
你好，我想请问下你。代码中为什么在求loss的时候给B和sigma加正则项，而论文里却没有说明，这里加正则项的作用是什么呀？  是不是为了保持正定可逆？
![图片](https://user-images.githubusercontent.com/55445846/66451887-e9c98880-ea90-11e9-9cc3-c18742416e6f.png)

**Comment by Cherishaca** [comment]
hello.Can you run the program properly?and the data requirements?

**Comment by ZhinanCai** [comment]
> 
> 
> hello.Can you run the program properly?and the data requirements?

yes, i can run it

**Comment by Cherishaca** [comment]
Can you add my Wechat or QQ? Some questions want to consult you, my QQ and Wechat: 1561442219. Thank you
